### ISSUE TITLE
windows平台下，cmd不能自动调起浏览器打开链接

### ISSUE THREAD

**Issue by Emily90** [athm-fe/create-autofe-app#1]
提示如图：
![image](https://cloud.githubusercontent.com/assets/3531512/21705045/41f4fd58-d3f8-11e6-8357-e7cbd167f3d1.png)

![image](https://cloud.githubusercontent.com/assets/3531512/21739299/ad09530c-d4d2-11e6-882f-5dc9af6b1a7d.png)

**Comment by hkongm** [comment]
https://github.com/jpuncle/create-autofe-app/blob/master/packages/autofe-scripts/gulpfile.js/config.js#L64

请自行更改 `google chrome` 为 `chrome` 再试试。

我们 windows 系统稀缺，😓

作者可以加个判断～

**Comment by hkongm** [comment]
汗，刚看到，曾经 assign 给我过。
