### ISSUE TITLE
import() 需要 webpack 的 publicPath 配置

### ISSUE THREAD

**Issue by jpuncle** [athm-fe/create-autofe-app#12]
有可能我们会需要 `import()` 或 `require.ensure` 来动态加载 chunk，而 chunk 加载的路径是需用通过 webpack 的 `publicPath` 来解析的。
需要考虑下这个玩意儿。

**Comment by hkongm** [comment]
需要结合实际使用情况评估，PC 站，哪里会如此异步？

**Comment by jpuncle** [comment]
@hkongm 那这个我延后支持吧
