### ISSUE TITLE
是否支持全局安装，或者提供桌面 App

### ISSUE THREAD

**Issue by jpuncle** [athm-fe/create-autofe-app#14]
毕竟 create-autofe-app 依赖的安装包还是很多的，导致下载时间比较长。

大家觉得是否需要考虑如下功能：
1. 支持全局安装
2. 基于 Electron 的桌面 App

**Comment by hkongm** [comment]
1. vote yes
2. vote no

**Comment by jpuncle** [comment]
1. 不提供 Electron 桌面 App
2. autofe-scripts 需要支持全局安装

**Comment by jpuncle** [comment]
移除 `regeneratorRuntime` 支持，目前 `autofe-scripts` 可以全局安装（v0.9.6 版本）
